config/routes.rb
EdadEditor::Application.routes.draw do
  get "lessons/index"

  resources :lessons
  

end

app/models/lesson.rb
class Lesson
  include Mongoid::Document
  field :title, :type => String
  field :course, :type => String
  field :course_code, :type => String
  field :professor, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end
  
  def new
    @lesson = Lesson.new
  end
  
  def create
    @lesson = Lesson.new(params[:lesson])
    
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to(lessons_path, :notice => 'Aula cadastrada com sucesso') }
        format.xml  { render :xml => @lesson, :status => :created, :location => @lesson }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EdadEditor</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/lessons/index.html.erb
<h1>Aulas</h1>
<p>Cadastre aqui novas aulas</p>

<%= link_to 'Nova aula', new_lesson_path %>

<div id="lessons">
  <% @lessons.each do |lesson| %>
    <%= lesson.title %><br />
  <% end %>
</div>

app/views/lessons/new.html.erb
<h1>Cadastro de Aulas</h1>

<%= form_for(@lesson) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :professor %>
    <%= f.text_field :professor %>
  </p>
  <p>
    <%= f.label :course %>
    <%= f.text_field :course %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>